# Generated by Django 2.1.10 on 2019-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('email', models.CharField(max_length=255, verbose_name='E-Mail')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザーID')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
