# Generated by Django 2.1.9 on 2019-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_auto_20190616_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='年齢'),
        ),
    ]
