# Generated by Django 2.1.10 on 2019-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0003_auto_20190616_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default=999, max_length=255, verbose_name='パスワード'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.CharField(default=999, max_length=255, verbose_name='ユーザーID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user_name',
            field=models.CharField(default=999, max_length=255, verbose_name='ユーザー名'),
            preserve_default=False,
        ),
    ]
