# Generated by Django 2.1.10 on 2019-08-31 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author_name', models.CharField(max_length=255, verbose_name='著者名')),
                ('book_attribute', models.CharField(max_length=255, verbose_name='感情')),
                ('book_id', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('book_title',),
            },
        ),
    ]
