# Generated by Django 2.1.10 on 2019-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author_name', models.CharField(max_length=255, verbose_name='著者名')),
                ('book_attribute', models.CharField(max_length=255, verbose_name='感情')),
                ('book_id', models.ManyToManyField(to='Crud.Account')),
            ],
            options={
                'ordering': ('book_title',),
            },
        ),
    ]
