# Generated by Django 2.1.10 on 2019-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='本ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author_name', models.CharField(max_length=255, verbose_name='著者名')),
                ('book_attribute', models.CharField(max_length=255, verbose_name='感情')),
                ('book_image', models.ImageField(default='None', upload_to='selbo')),
            ],
            options={
                'ordering': ('book_title',),
            },
        ),
    ]
